### ISSUE TITLE
For beta, print warning and exit early if starting a service includes a dependency that is already running

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/devservices#98]
Say that we have relay running, then we run snuba. Snuba depends on shared redis and kafka instances, and we currently don't have a good way to differentiate stopping relay/snuba after both services are running. For now, add a warning and exit early that looks something like:

"You are currently starting a service that has a dependency that is already running. Please stop that service before proceeding. This will be supported in the future :)"

**Comment by IanWoodard** [comment]
Note: This does not impact starting Sentry, which brings up both relay and snuba, but instead prevents starting snuba and relay independently for now while we figure out how we want to handle this case in the future.

**Comment by hubertdeng123** [comment]
not needed for beta with https://github.com/getsentry/devservices/pull/104
